name: Build Executable

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build Executable
      run: |
        pyinstaller --onefile --name=MyApp main.py
        echo "Build completed - checking files:"
        dir dist\
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyApplication
        path: dist/MyApp.exe